Repository freeCodeCamp/how-to-contribute-to-open-source, pull requests merged in 2020-11, with the labels that each got.

#478 Update README-FA.md
  README-FA.md
Labels: in progress

#467 Making translation Readme guide: README-ID.md
  README-ID.md
Labels: in progress, ready for QA

#487 Translated README.md to Hebrew
  README-HE.md
Labels: ready for QA

#483 Translated README-MS.md to Malay Language
  README-MS.md
Labels: in progress, ready for QA
